include:
  # - board: corneish_zen_v2_left
  # - board: corneish_zen_v2_right
# dongle corne
  - board: nice_nano_v2
    shield: crpd_central_left ssd1306_128x64_spi 
  - board: nice_nano_v2
    shield: crpd_right ssd1306_128x64_spi
# reset settings
  - board: nice_nano_v2
    shield: settings_reset
