include:
  # - board: corneish_zen_v2_left
  # - board: corneish_zen_v2_right
# dongle corne
  - board: seeeduino_xiao_ble
    shield: corne_dongle prospector_adapter
  - board: nice_nano_v2
    shield: corne_central_left
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
# reset settings
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
