include:
  - board: nice_nano_v2
    shield: nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: nice_view_adapter nice_view
# reset settings
  - board: nice_nano_v2
    shield: settings_reset
