include:
  - board: nice_nano_v2
    shield: crpd_central_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: crpd_right nice_view_adapter nice_view
# reset settings
  - board: nice_nano_v2
    shield: settings_reset
