include:
  # - board: corneish_zen_v2_left
  # - board: corneish_zen_v2_right
# dongle corne
  - board: nice_nano_v2
    shield: crpd_central_left nice_view
  - board: nice_nano_v2
    shield: crpd_right nice_view
# reset settings
  - board: nice_nano_v2
    shield: settings_reset
